### PR TITLE
Avoid using force-unwraps of Optionals during .unwrap()

### PR DESCRIPTION
**Pull request by Willamin**
#trivial

### CODE REVIEW

**Comment by MortyMerr** [comment]
Hi @Willamin thanks for contribution.
`.filter { $0 != nil }.map { $0!` can be replaced with `.compactMap`

**Comment by freak4pc** [comment]
As Anton mentioned, `.unwrap` should not be used at this point since we we have `compactMap`. `unwrap` will be deprecated in a coming version of RxSwiftExt, but I think we should also make it use `compactMap` internally just so we're clear on it.

**Comment by freak4pc** [comment]
Do any of you want to make this use `compactMap` for now ?

**Comment by MortyMerr** [comment]
Sure, here https://github.com/RxSwiftCommunity/RxSwiftExt/pull/234

**Pull request closed without merging**
