### PR TITLE
Swift 4.0 + RxSwift 4.0.0

### PR DESCRIPTION
**Pull request by bobgodwinx**
- [x] Completed migration to `Swift 4.0` 
- [x] Completed migration to `RxSwift 4.0.0-rc.0`
- [x] Fixed all failing specs due from migration

### CODE REVIEW

**Comment by fpillet** [comment]
Cool stuff! Let me know when you're done pushing stuff, I'll review & merge. Thanks!

**Comment by bobgodwinx** [comment]
@fpillet I will pin you. when done. Travis is giving me some headaches let's see if everything builds after this last commit.

**Comment by bobgodwinx** [comment]
Over to you @fpillet see if you fix the `travis` issue I can't figure why it's no building correctly. All the commands works locally. You can review it. Let me know what you think.

**Comment by reloni** [comment]
It seems carthage [don't recognise spaces](https://github.com/Carthage/Carthage/issues/1756). Try `--platform ios,tvos`.

**Comment by bobgodwinx** [comment]
@reloni Thanks for the info let's configure it as indicated in the [https://github.com/Carthage/Carthage/issues/1756](url)

**Comment by bobgodwinx** [comment]
@fpillet we have green light 👍 take a look

**Comment by fpillet** [comment]
Excellent, thanks! Just need to target the just-released 4.0.0 and we can release :)
👍

**Pull request merged**
