### PR TITLE
Implements errors() & elements() for materialized Observable

### PR DESCRIPTION
**Pull request by TheAdamBorek**
Description in the issue #81

### CODE REVIEW

**Comment by TheAdamBorek** [comment]
Hmmmm.... It doesn't see `EventConvertible` type...  @fpillet do you know why?
Locally everything is ok ... 🤔

**Comment by fpillet** [comment]
Because we need to update the podspec to use RxSwift 3.4 minimum?

**Comment by TheAdamBorek** [comment]
@fpillet should I include that also in the PR? I haven't released the lib to cocoa pods before 😅

**Comment by reloni** [comment]
If you will update RxSwift version, update also cartfile: `github "ReactiveX/RxSwift" ~> 3.4.0`

**Comment by fpillet** [comment]
Good point, @reloni

**Comment by fpillet** [comment]
Pushed with ah update to Podspec / Cartfile. Let's give CI some time to complete. Thanks @TheAdamBorek !

**Pull request merged**
