### PR TITLE
RepeatBehavior documentation update

### PR DESCRIPTION
**Pull request by anton-plebanovich**
- Updates RepeatBehavior documentation to be in correspondence with RxSwift retry operator and the current logic

### CODE REVIEW

**Comment by anton-plebanovich** [comment]
Fixing CI was a nice quest lol 🤣

**Comment by anton-plebanovich** [comment]
@freak4pc could you have a look? It's just documentation change, warning fixes, and CI fixes. The logic wasn't updated.

**Review by freak4pc — APPROVED** [review]
Thanks! 
I'm approving because you waited for a while but next time - this is really 3 separate PRs. 

Doc updates, CI fixes, Carthage updates - they don't really fit in the same PR.

Thank you!

**Comment by anton-plebanovich** [comment]
@freak4pc Got it thanks

**Pull request merged**
