### PR TITLE
[Proposal] Deprecates mapTo in favor of map(to:).

### PR DESCRIPTION
**Pull request by noppefoxwolf**
# Proposal

In `RxSwift`, `bindTo` was become `bind(to:)` at 3.4.0.
In the same way, I think that `mapTo` should be `map(to:)`.

### CODE REVIEW

**Comment by fpillet** [comment]
Good thinking! Would you mind amending your PR with an update to the Playground example page for `mapTo` (index will need an update as well) and the README ? Thanks!

**Comment by noppefoxwolf** [comment]
@fpillet 
Thank you for your response.
Fix Playground and Readme.
The file name of Playground remains `mapTo.xcplaygroundpage`, but is there a problem?
This is because it is hard to distinguish from the original `map`.

**Comment by fpillet** [comment]
Nearly there! Link to the `map(to:)` page from playground Index page is still broken. Other than this, changes are 👍

**Comment by fpillet** [comment]
That was fast. Thanks!

**Comment by noppefoxwolf** [comment]
@fpillet Thank you for your polite response.

**Pull request merged**
