### PR TITLE
PausableBuffered

### PR DESCRIPTION
**Pull request by tgyhlsb**
http://rxmarbles.com/#pausableBuffered

~~Implementation from existing `pausable` operator.~~

Use @mkko implementation https://github.com/RxSwiftCommunity/RxSwiftExt/issues/77

### CODE REVIEW

**Comment by LuizZak** [comment]
I've noticed that if the pauser ticks false then true it duplicates the latest emission from source, is this desirable/expected?

**Comment by tgyhlsb** [comment]
You're right, this is what I needed but it's not what RxMarbles describes. I'll work on a fix. Thanks

**Comment by tgyhlsb** [comment]
You are etting closer to the expected behavior. But according to RxMarbles, `pausableBuffered` must complete when both the` source` and the `pauser` complete. This implementation completes as soon as the `source` complete.

**Comment by tgyhlsb** [comment]
Which I fixed with 

```swift
public func pausableBuffered<P : ObservableType> (_ pauser: P) -> Observable<E> where P.E == Bool {
    
    return Observable<E>.create { observer in
        var latest: E? = nil
        var paused = true
        var completeCount = 0
        let lock = NSRecursiveLock()
        
        let boundaryDisposable =
            pauser
                .distinctUntilChanged()
                .subscribe { event in
                    lock.lock(); defer { lock.unlock() }
                    switch event {
                    case .next(let resume):
                        paused = !resume
                        
                        if resume {
                            if let el = latest {
                                observer.onNext(el)
                                latest = nil
                            }
                        }
                    case .completed:
                        completeCount += 1
                        if completeCount == 2 {
                            observer.onCompleted()
                        }
                    case .error(let error):
                        observer.onError(error)
                    }
        }
        
        let disposable = self.subscribe { event in
            lock.lock(); defer { lock.unlock() }
            switch event {
            case .next(let element):
                if paused {
                    latest = element
                } else {
                    observer.onNext(element)
                }
            case .completed:
                completeCount += 1
                if completeCount == 2 {
                    observer.onCompleted()
                }
            case .error(let error):
                observer.onError(error)
            }
        }
        
        return Disposables.create([disposable, boundaryDisposable])
    }
    
}
```

**Comment by tgyhlsb** [comment]
[RxJS pausableBuffered](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/backpressure/pausablebuffered.js) replays all the elements that occured during the pause which is not what's expected. They also forward the `pauser` errors which can be good, RxMarbles says nothing about it.

For now I'll update my PR with your implementation.

**Comment by LuizZak** [comment]
Hmm I guess we can make a buffered variant that emits all elements too, like so:

```swift
/// Pauses the elements of the source observable sequence based on the latest
/// element from the second observable sequence.
///
/// Elements are passed if the latest value emitted from `pauser` is `true`,
/// or else they are buffered such that when `pauser` emits `true` all elements
/// are flushed as single events in a contiguous stream.
///
/// While `pauser` is `true`, elements emitted are always emitted as a single-element
/// array containing the element emitted from the source observable.
///
/// - parameter pauser: The source observable to use when pausing the elements.
/// - Returns: An observable that pauses when `pauser` emits `false`, and holds
/// onto the latest elements emitted from the source observable until `pauser`
/// resumes by emitting `true` again.
func pausableBufferedFlattened<P: ObservableType>(_ pauser: P) -> Observable<E> where P.E == Bool {
    return pausableBufferedFlattened(pauser, limit: -1)
}

/// Pauses the elements of the source observable sequence based on the latest
/// element from the second observable sequence.
///
/// Elements are passed if the latest value emitted from `pauser` is `true`,
/// or else they are buffered such that when `pauser` emits `true` all elements
/// are flushed as single events in a contiguous stream.
///
/// While `pauser` is `true`, elements emitted are always emitted as a single-element
/// array containing the element emitted from the source observable.
///
/// - Parameters:
///   - pauser: The source observable to use when pausing the elements.
///   - limit: The maximum number of elements to send down the paused observable
/// once it emits something. When the limit is reached, earlier elements are
/// discarded from the result to give space to the latest elements.
/// Use -1 to indicate an indefinite buffering limit.
/// *Note:* Must be `>= 1` or `-1`.
/// - Returns: An observable that pauses when `pauser` emits `false`, and holds
/// onto the latest elements emitted from the source observable until `pauser`
/// resumes by emitting `true` again.
func pausableBufferedFlattened<P: ObservableType>(_ pauser: P, limit: Int) -> Observable<E> where P.E == Bool {
    
    return Observable<E>.create { observer in
        var buffer: [E] = []
        buffer.reserveCapacity(limit)
        
        var paused = false
        
        let lock = NSRecursiveLock()
        
        let boundaryDisposable = pauser.subscribe { event in
            lock.lock(); defer { lock.unlock() }
            switch event {
            case .next(let resume):
                paused = !resume
                
                if resume && buffer.count > 0 {
                    for value in buffer {
                        observer.onNext(value)
                    }
                    buffer.removeAll(keepingCapacity: true)
                }
            case .completed:
                observer.onCompleted()
            case .error(let error):
                observer.onError(error)
            }
        }
        
        let disposable = self.subscribe { event in
            lock.lock(); defer { lock.unlock() }
            switch event {
            case .next(let element):
                
                if paused {
                    buffer.append(element)
                    if limit != -1 && buffer.count > limit {
                        buffer.remove(at: 0)
                    }
                } else {
                    observer.onNext(element)
                }
                
            case .completed:
                // Flush remaining items
                if buffer.count > 0 {
                    for value in buffer {
                        observer.onNext(value)
                    }
                }
                observer.onCompleted()
                
            case .error(let error):
                observer.onError(error)
                buffer.removeAll(keepingCapacity: false)
            }
        }
        
        return Disposables.create([disposable, boundaryDisposable])
    }
}
```

**Comment by LuizZak** [comment]
This is pretty bulky, but allows buffering like rxmarbles' `pausableBuffered`

**Comment by tgyhlsb** [comment]
Do we really want to flush on `.completed` for the source ?

If we are paused we are not expecting any event so why flush ? If we are not paused on `.completed`, the buffer is empty there is nothing to flush.

I don't know what the expected, still new with Rx. RxJS flushes on both `error` and `completed`.

**Comment by tgyhlsb** [comment]
```swift
/**
 Pauses the elements of the source observable sequence based on the latest element from the second observable sequence.
 
 While paused, elements from the source are buffered, limited to a maximum number of element.
 
 When resumed, all bufered elements are flushed as single events in a contiguous stream.
 
 - seealso: [pausable operator on reactivex.io](http://reactivex.io/documentation/operators/backpressure.html)
 
 - parameter pauser: The observable sequence used to pause the source observable sequence.
 - parameter limit: The maximum number of element buffered. Pass `nil` to buffer all elements withou limit.
 - returns: The observable sequence which is paused based upon the pauser observable sequence.
 */
func pausableBuffered<P: ObservableType>(_ pauser: P, limit: Int? = 1) -> Observable<E> where P.E == Bool {
    
    return Observable<E>.create { observer in
        var buffer: [E] = []
        if let limit = limit {
            buffer.reserveCapacity(limit)
        }
        
        var paused = false
        let lock = NSRecursiveLock()
        
        let flush = {
            for value in buffer {
                observer.onNext(value)
            }
            buffer.removeAll(keepingCapacity: limit != nil)
        }
        
        let boundaryDisposable = pauser.subscribe { event in
            lock.lock(); defer { lock.unlock() }
            switch event {
            case .next(let resume):
                paused = !resume
                
                if resume && buffer.count > 0 {
                    flush()
                }
            case .completed:
                observer.onCompleted()
            case .error(let error):
                observer.onError(error)
            }
        }
        
        let disposable = self.subscribe { event in
            lock.lock(); defer { lock.unlock() }
            switch event {
            case .next(let element):
                
                if paused {
                    buffer.append(element)
                    if let limit = limit, buffer.count > limit {
                        buffer.remove(at: 0)
                    }
                } else {
                    observer.onNext(element)
                }
                
            case .completed:
                flush()
                observer.onCompleted()
                
            case .error(let error):
                flush()
                observer.onError(error)
            }
        }
        
        return Disposables.create([disposable, boundaryDisposable])
    }
}
```

**Comment by LuizZak** [comment]
Looks good!

**Comment by LuizZak** [comment]
Maybe add a parameter to toggle whether or not to flush remaining items, other than that LGTM

**Comment by tgyhlsb** [comment]
LGTM too, thanks for your help ;)

**Comment by fpillet** [comment]
Sorry for the delay! Looking into merging this now!

**Pull request merged**
