### PR TITLE
add a pausable(afterCount:) operator

### PR DESCRIPTION
**Pull request by twittemb**
The pause is available only after a certain count of events. Before the number of emitted events reaches that count the Pauser will not be taken care of. When the Pauser is active, elements are ignored unless the second sequence has most recently emitted `true`, this becomes the same behavior as the normal pausable operator.

### CODE REVIEW

**Comment by twittemb** [comment]
Hi 

I don't know if that kind of operator could be useful (it is on my project RxFlow :-)) ... 
Anyway I have some issue writing the unit tests. Any help would be appreciated 👍

**Comment by twittemb** [comment]
Hi @freak4pc ... Do you think this PR has an interest ?

Thx.

**Comment by freak4pc** [comment]
@twittemb I just want to confirm, this operator would pause until a certain number of emissions occur on a second Observable ? Didn't really have time to review this and the other guys have been kind of busy lately it seems :)

**Comment by twittemb** [comment]
Hi @freak4pc 
What it does is: the pauser observable is ignored until the first observable has trigger the "aftetCount" number of events.

It is useful to be sure that the first observable will trigger something before being pausable.

**Comment by freak4pc** [comment]
I really want to help out here but I don't have enough experience with the original pausable operator at all :( If someone else could poke at this that'd be great, otherwise I'll see what I can do next week.

**Comment by twittemb** [comment]
Hi here,

just a little UP on this PR 😀

It is OK to drop it if there is no value to bring to this repo.

**Comment by fpillet** [comment]
@twittemb don't close it! We're just being a little overwhelmed :)

**Comment by freak4pc** [comment]
The main issue with the specific one is that I just have no understanding of how it works and what it does so I prefer not to review it - if there's someone who does :)

**Comment by MortyMerr** [comment]
Hey @twittemb I added tests on your operator and extend generic type name. Also I updated readme to include a new operator. Please approve that you r ok with these changes.

**Comment by MortyMerr** [comment]
Hey @freak4pc could u please check this? I resolved conflicts. I am not sure about motivation to add this, so both close/merge is ok for me

**Pull request closed without merging**
