### PR TITLE
#trivial Update map(to: ) to mapTo in the readme

### PR DESCRIPTION
**Pull request by ericmarkmartin**

### CODE REVIEW

**Comment by freak4pc** [comment]
Thanks @ericmarkmartin ! Can you fix this as well ? https://github.com/RxSwiftCommunity/RxSwiftExt/blob/1a7cf0f73dbac48713501ddeee2ccad871ddfa37/Playground/RxSwiftExtPlayground.playground/Pages/mapTo.xcplaygroundpage/Contents.swift#L16

**Comment by ericmarkmartin** [comment]
Will do

**Comment by freak4pc** [comment]
Thanks @ericmarkmartin ! And welcome to RxSwiftCommunity ! 🏆

**Comment by ericmarkmartin** [comment]
Thank you for all the great tools and glad to be here!

**Pull request merged**
