### PR TITLE
Added Observable+Alias.swift to project file with correct targets. #trivial

### PR DESCRIPTION
**Pull request by adamsousa**
Observable-Alias.swift was missing targets and references in the project file. Added in this PR

#trivial

### CODE REVIEW

**Comment by freak4pc** [comment]
Thanks for the fix, but I'm not sure adding it to the project is relevant at all to fetching it via SPM or even CocoaPods. It's only for the Sample Project itself, unless you're referring to Carthage?

**Comment by adamsousa** [comment]
We are using Carthage, I wasn't able to rebuild this framework until this file was added to the project file.

**Comment by marcbaldwin** [comment]
I was also unable to build this framework using Carthage. Thanks for the fix, now that Xcode15 has been released, it'd be great to get this released too 🙏

**Comment by freak4pc** [comment]
Thanks!

**Pull request merged**
