### PR TITLE
Remove flatMapSync operator

### PR DESCRIPTION
**Pull request by MortyMerr**
https://github.com/RxSwiftCommunity/RxSwiftExt/issues/212

### CODE REVIEW

**Comment by jdisho** [comment]
I think you should remove the tests too. @MortyMerr

**Comment by MortyMerr** [comment]
This PR is blocked by https://github.com/RxSwiftCommunity/RxSwiftExt/pull/214

**Comment by freak4pc** [comment]
@MortyMerr Just some conflicts here

**Comment by MortyMerr** [comment]
@freak4pc fixed :)

**Pull request merged**
