### PR TITLE
[Proposal] flatMapMany Operator

### PR DESCRIPTION
**Pull request by touyu**
### Motivation for inclusion

For example, if you want to perform asynchronous processing on each element of observable array, write as follows:

```swift
// `fetch()` is asynchronous processing and returns observable value.
theObservable
  .flatMap { array in 
    let new = array.map { $0.fetch() }
    return Observable.from(new).merge().toArray()
  }
```
I want to write the above code more concisely:
```swift
theObservable
  .flatMapMany { $0.fetch() }
```

### Example of use
It is described above.

### CODE REVIEW

**Comment by freak4pc** [comment]
Hey @touyu - Thanks for the suggestion and implementation.
I'm personally quite torn and currently adding against such an operator. 

The issue is - as opposed to `mapMany` on `map` - `flatMap` creates additional resources / on-air streams. Using an operator that can create so many resources in a way that's "masked" into such a simplistic operator feels very very dangerous in the hands of 90% of users. 

Unless there is demand from community, or other opinions, I'd currently be against merging this unfortunately. 

Inviting @RxSwiftCommunity/contributors to comment their thoughts. 

Thanks again!

**Comment by jdisho** [comment]
Nice idea! Looks good to me!

**Comment by freak4pc** [comment]
@jdisho Please re-read my message.

`mapMany` is 100% fine. It does a simple non-escaping mapping from `[T]` to `[R]`. 

`flatMap`, on the other hand, creates new subscriptions (e.g. resources) on every run. To "hide" this fact under a simplistic operator such as `flatMapMany` is dangerous since people will not be aware of what this does. 

```swift
array.
 flatMapMany { doLongProcess(with: $0) } 
```

Now thing of this:
```
array is [1, 2, 3] -> 3 running calls
array changes to [4, 5, 6] -> 6 running calls
array emits arbitrary 20 calls -> 26 running calls
```

This kind of exponential increase in resources will be hidden inside this operator where the consumer of it (a developer) wouldn't usually know or understand the performance cost of it (not would be able to debug it without going into the operator implementation). 

And on, and on, there is no disposition (since its not a flatMapLatest), unless the inner requests completes. Also, his implementation includes a `toArray` which means its too opinionated (it doesn't just flatMaps, it also must be a finite sequence). 

In my eyes it's too niche, too dangerous for usage and doesn't provide too many benefits over writing the full expression where you have control and explicitness.

**Comment by jdisho** [comment]
Thank you for the explanation 😊 @freak4pc

**Comment by jdisho** [comment]
What about this @freak4pc ?

```swift 
public func flatMapMany<O>(_ selector: @escaping (Self.E.Element) -> O) -> Observable<[O]> {
        return flatMapLatest { collection -> Observable<[O]> in
            let new = collection.map(selector)
            return Observable.just(new)
        }
    }
```

**Comment by freak4pc** [comment]
I’m not sure how it’s solving the issue or is different than mapMany. My opinion is that in general this kind of helper would be much more harm than good.

**Comment by touyu** [comment]
Thank you for confirming this PR.

Is it still dangerous with the following code?

```swift
public func flatMapMany<O>(_ selector: @escaping (E.Element) throws -> O) -> Observable<[O.E]> where O: ObservableType {
    return flatMap { collection -> Observable<[O.E]> in
        let new = try collection.map(selector)
        return Observable.zip(new)
    }
}
```

**Comment by freak4pc** [comment]
Hey all - I'm currently leaning towards closing this PR. Even though I'm very happy and appreciative of the work put into this, it's just too risky to mask flatMap(s) and resource-creation that way IMO. There also doesn't seem to be another other requests for this sort of operator in this history of Ext. If there's no other feedback in the next 24hrs or so, I'll be closing this. Thanks !

**Pull request closed without merging**
