### PR TITLE
OfType Operator

### PR DESCRIPTION
**Pull request by glwithu06**
- Implement `ofType` operator using `filter` and `map` operator.
- Add `ofType` extension methods on `ObservableType`

### CODE REVIEW

**Comment by glwithu06** [comment]
Actually, I have implemented this operator in `RxSwift`.
And @kzaher said, `RxSwiftExt` is a better place to put this functionality.
Here is my PR on `RxSwift`. (https://github.com/ReactiveX/RxSwift/pull/1529)

**Comment by freak4pc** [comment]
Didn't have time to look into this one yet, sorry about that. Hope to find some time later :) 
In general though, I would name it `filterType` or `takeType` and not `ofType`, since the former is in-line for discovery of filtering operators usually.

**Comment by freak4pc** [comment]
@glwithu06 Let me know if you still want to add this one. 

If we call it `filterType` or `takeType` ( I think the latter makes more sense ), I'm good with adding it :)

**Comment by jegnux** [comment]
Oops, I didn't see this PR and open a similar one. But let's keep the discussion here.
In my PR I called they operator `filterMap(as:)`
Here is why I think it's the best option.

- `filterType`, `takeType` and `ofType` doesn't reflect imho that the result is actually map
- `filterMap` does reflect this information
- `as` is common to express casting in swift world
- `filterMap(as:)` matches the name style of `map(to:)`

WDYT?

**Comment by freak4pc** [comment]
I'm not super religious to this, I get your point here, but I'm not entirely sure. 
I consider the fact its a map to be an implementation detail, while the main idea of it is it would not pass items that are not of a certain type. 

takeType wouldn't fit here since take has the "termination" kind of behavior, so I think it stands between 

`filterType(Int.self)` vs. `filterMap(as: Int.self)` 

@fpillet if you have a minute would love your call here :) I think we need a third set of eyes

**Comment by jegnux** [comment]
> takeType wouldn't fit here since take has the "termination" kind of behavior,

I'm not sure to understand.`take()` or `takeWhile()` indeed change how the original sequence is completed. But that's not the case of this new operator. This new operator completes when the original sequence completes.

**Comment by jegnux** [comment]
Hum... mixed feelings coming... It seems that other Rx implementations of this operator use `ofType` as suggested by @glwithu06 

http://reactivex.io/documentation/operators/filter.html

What's the policy of RxSwiftExt? Do we want to match as much as possible other Reactive X implementations?

**Comment by freak4pc** [comment]
Blah, I don't like that name :( Not entirely sure on policy here but we can go with ofType if its already common.

**Comment by jegnux** [comment]
Personally I won’t mind to have a different name than other implementation. 
We could also implement both (ofType and filterMap(as:))

We already have ignoreErrors() in RxSwiftExt as an alias to retry() and RxSwift has debounce() and throttle() that do the same thing.

**Comment by bobgodwinx** [comment]
😂 Naming convention the most difficult aspect of software engineering 😂  now don't shoot me alive but after reading the entire thread this is my suggestion IMHO I would name it as follows.
- ` public func whereType<T>(_ type: T.Type) -> Observable<T> `
Somehow it sounds cool 😎 or whatever 👍

**Comment by freak4pc** [comment]
I don't like that - it doesn't belong to any family of operators from Rx at all. 

I think I agree with @jegnux - to my distaste (🤣), let's make it ofType to conform to RxJava so users of it can find their way easily.

**Comment by jegnux** [comment]
@bobgodwinx I agree with @freak4pc, `where` doesn't have any precedence in Rx world.

>I think I agree with @jegnux
@freak4pc ok to have both `filterMap(as:)` and `ofType()` ?
I strongly believe `filterMap(as:)` is a good choice. It's basically the condensed version of what it does ( `.filter { $0 is T }.map { $0 as! T }`). #lobbying

**Comment by bobgodwinx** [comment]
@freak4pc @jegnux I totally agree that `whereType()` is `SQL` thing 😂 , `ofType()`  on the other hand is bit grrrrrrr. Yes `filterMap(as:)` might fit. I would go with that. 👍

**Comment by freak4pc** [comment]
Let’s go for ofType with an alias with filterMap(as:) and cover all basis :)

**Comment by jegnux** [comment]
A consensus, great !
Now the question is, do we go with my PR (#139) or this one?

**Comment by freak4pc** [comment]
@jegnux since you seem to be available, and no response from OP here, let’s wrap up your PR

**Comment by glwithu06** [comment]
Oops! Sorry for very late response.
I was away for a while.
Anyway we decided to go for 'ofType'. right?

**Comment by freak4pc** [comment]
Hey @glwithu06 - Could you please 

1. Rebase your changes so the merge commit is gone (If you don't know how I can take care of it later worst case)

2. Fix the CI so build passes successfully :) 

Thanks !

**Comment by fpillet** [comment]
I'm fine with `ofType(_:)`, I don't have a better idea to name this operator !

**Comment by freak4pc** [comment]
Made a tiny adjustment to the CHANGELOG (method signature was wrong). 
This looks great ! Thanks for your work @glwithu06, and welcome to RxSwiftCommunity!

**Pull request merged**
