### PR TITLE
Change `filterMap(transform:)` callback signature on throwing

### PR DESCRIPTION
**Pull request by MortyMerr**
Based on https://github.com/RxSwiftCommunity/RxSwiftExt/pull/185

### CODE REVIEW

**Comment by freak4pc** [comment]
I don't find it a good idea to change several operators in the same PR. If you want to change flatMapSync, please make a separate PR for that, and then we can discuss filterMap separately. Thanks.

**Comment by MortyMerr** [comment]
@freak4pc `filterMap` is based on `flatMapSync`. It's impossible to change them separately. In original  #185 PR it wasn't a problem. 
If you want, I will split this PRs, but I can't see any sense in that

**Comment by freak4pc** [comment]
That's my point. we might want to alter `filterMap` first (see my comment in #212).

**Comment by MortyMerr** [comment]
@freak4pc get it. Is it ok to alter `filterMap` without touching `flatMapSync` right now?

**Comment by freak4pc** [comment]
Yes. Let's close this PR and make a separate PR for `filterMap` changes I suggested on the other PR.

**Pull request closed without merging**
