### PR TITLE
Add distinct, mapTo and not operator to Driver instances

### PR DESCRIPTION
**Pull request by RafaelPlantard**
To solve issue: #64.
I also separate RxSwift from RxCocoa domains to avoid compatibility issues.
All RxCocoa features (Driver support) is available from `RxSwiftExt/RxCocoa` subspec.

### CODE REVIEW

**Comment by patrickbdev** [comment]
This is a great idea and very useful! Hoping it can be merged in @fpillet 👍

**Comment by RafaelPlantard** [comment]
Thanks @patrickbdev

**Comment by fpillet** [comment]
Sure! Sorry guys forgot to merge this one.

**Comment by patrickbdev** [comment]
Thanks @fpillet, will you be pushing an update to cocoapods as well?

**Comment by fpillet** [comment]
Yes going to happen this morning

**Pull request merged**
