### PR TITLE
Add skipLast operator

### PR DESCRIPTION
**Pull request by MortyMerr**
Based on https://github.com/ReactiveX/RxSwift/issues/1957

### CODE REVIEW

**Comment by freak4pc** [comment]
Hey, let's not do anything until there's a final answer in Core.

**Comment by MortyMerr** [comment]
Sure.

**Comment by MortyMerr** [comment]
Hey @freak4pc as I understand, core repo won't approve this operator. What do u think?

**Comment by freak4pc** [comment]
Not really seeing a practical use-case / demand for this operator. Can you share either?

**Comment by MortyMerr** [comment]
Also can't see, just fulfilling the user request. So, should we close this one?

**Comment by freak4pc** [comment]
Yup, feels like a good idea to me for the time being.

**Pull request closed without merging**
